# !/bin/bash
pip install -r requirements.txt 
# cd /Thesis/source
# python main_train_up.py --device cuda --model RNN --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model RNN --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model RNN --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model RNN --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model RNN --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model RNN --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model GRU --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model GRU --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model GRU --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model GRU --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model GRU --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model GRU --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model LSTM --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model LSTM --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model LSTM --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model LSTM --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model LSTM --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model LSTM --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model Dipole --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model Dipole --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model Dipole --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model Dipole --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model Dipole --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model Dipole --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model Retain --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model Retain --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model Retain --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model Retain --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model Retain --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model Retain --device cuda --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model HiTANet1L --keys 'reverse_time' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model HiTANet1L --device cuda --keys 'reverse_time' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model HiTANet1L --device cuda --keys 'reverse_time' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model HiTANet1L --device cuda --keys 'reverse_time' --metric_name 'classification_report' --batch_size 64 --top_k 15 
# python main_evaluate_up.py --model HiTANet1L --device cuda --keys 'reverse_time' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model HiTANet1L --device cuda --keys 'reverse_time' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.0001 --patience 5 --with_clip 0.5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_CAT --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Emb --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_GRU_Sopliot --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.0001 --patience 5 --with_clip 0.5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v1 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.0001 --patience 5 --with_clip 0.5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v3 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v4 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v5 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v6 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_2_c --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v7 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v8 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Only_1_v9 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25 
# python main_train_up.py --device cuda --model TCNN1L --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TCNN1L --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5 
# python main_evaluate_up.py --model TCNN1L --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model TCNN1L --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model TCNN1L --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model TCNN1L --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TCNN1LV --keys 'reverse_time' 'age' --epochs 100 --batch_size 24 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TCNN1LV --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --model TCNN1LV --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TCNN1LV --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TCNN1LV --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TCNN1LV --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.0001 --patience 5
# python main_evaluate_up.py --model TTT --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --model TTT --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TTT --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TTT --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TTT --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TTT_Time --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TTT_Time --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TTT_Time --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TTT_Time --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_evaluate_up.py --model TTT_Time --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_train_up.py --device cuda --model TTT_Time_RELU --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TTT_Time_RELU --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --model TTT_Time_RELU --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TTT_Time_RELU --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TTT_Time_RELU --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TTT_Time_RELU --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Embed --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TTT_Time_Embed --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --model TTT_Time_Embed --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TTT_Time_Embed --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TTT_Time_Embed --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TTT_Time_Embed --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Multi_scale_CNN --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TTT_Time_Multi_scale_CNN --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --model TTT_Time_Multi_scale_CNN --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --model TTT_Time_Multi_scale_CNN --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --model TTT_Time_Multi_scale_CNN --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --model TTT_Time_Multi_scale_CNN --category_map_state True --device cuda --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Norm --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_Noise --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction FocalLoss01 --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_01 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction FocalLoss005 --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_005 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction FocalLoss015 --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F_015 --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True  --category_map_state True --keys 'reverse_time' 'age' --epochs 100 --batch_size 64 --lossfunction FocalLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 5
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 10
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 15
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 20
# python main_evaluate_up.py --device cuda --model TTT_Time_Ensemble_Multiscale_Decoder_F --category_type_map_state True --category_map_state True --keys 'reverse_time' 'age' --metric_name 'classification_report' --batch_size 64 --top_k 25
# python main_train_up.py --device cuda --model TimeLSTM --keys 'reverse_time' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --learning_rate 0.001 --patience 5
# python main_evaluate_up.py --model TimeLSTM --device cuda --metric_name 'classification_report' --batch_size 32 --top_k 5
# python main_evaluate_up.py --model TimeLSTM --device cuda --metric_name 'classification_report' --batch_size 32 --top_k 10
# python main_evaluate_up.py --model TimeLSTM --device cuda --metric_name 'classification_report' --batch_size 32 --top_k 15
# python main_evaluate_up.py --model TimeLSTM --device cuda --metric_name 'classification_report' --batch_size 32 --top_k 20
# python main_evaluate_up.py --model TimeLSTM --device cuda --metric_name 'classification_report' --batch_size 32 --top_k 25
# python main_train_up.py --device cuda --model AHiTANet --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 5
# python main_train_up.py --device cuda --model TCNN --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 5
# python main_train_up.py --device cuda --model HiTANet --keys 'reverse_time' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 5
# python main_train_up.py --device cuda --model TCNN5 --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 5
# python main_train_up.py --device cuda --model TCNNF --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 10
# python main_train_up.py --device cuda --model TCNNG --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 10
# python main_train_up.py --device cuda --model TCNNG5 --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 10
# python main_train_up.py --device cuda --model TCNNGS3 --keys 'reverse_time' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5 --learning_rate 0.0001 --patience 5
# python main_train_up.py --device cuda --model BHiTANet --keys 'reverse_time' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True --with_clip 0.5
# python main_train_up.py --device cuda --model GAHiTANet --keys 'reverse_time' 'gender' 'age' --epochs 100 --batch_size 32 --lossfunction CrossEntropyLoss --shuffle True
# python main_train_up.py --device cuda --model HiTANet --keys 'reverse_time' --epochs 100 --batch_size 32 --lossfunction BCEWithLogitsLoss --shuffle True
